;
;   WINDOW SKIN for MenuetOS
;   ivan-yar@bk.ru
;

_skinh          dd      22

_refleft        dd      0
_skinleft       dd      0
_skinleftw      dd      3

_refbase        dd      0
_skinbase       dd      3
_skinbasew      dd      8

_refoper        dd      0
_skinoper       dd      -21
_skinoperw      dd      21

_buttonCx       dd      2            ; close
_buttonCy       dd      3
_buttonCw       dd      17
_buttonCh       dd      17

;_buttonMx       dd      26           ; minimize/maximize
;_buttonMy       dd      4
;_buttonMw       dd      14
;_buttonMh       dd      14

;_buttonPx       dd      43           ; p
;_buttonPy       dd      4
;_buttonPw       dd      14
;_buttonPh       dd      14

_colorframe     dd      0x005E9625
_colorborder    dd      0x003C6B0D
_coloroutborder dd      0x003C6B0D

_fileleft       db      'LEFT.BMP     '
_filebase       db      'BASE.BMP     '
_fileoper       db      'OPER.BMP     '

_skinwinw       dd      0
