   
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                                          ;;
;;   WINDOW SKIN for MenuetOS               ;;
;;                                          ;;
;;   entryway@bkg.lt                        ;;
;;                                          ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
   
   
   
_skinh          dd      22
   
_refleft        dd      0
_skinleft       dd      0
_skinleftw      dd      66
   
_refbase        dd      0
_skinbase       dd      66
_skinbasew      dd      10
   
_refoper        dd      0
_skinoper       dd      -58
_skinoperw      dd      58
   
_buttonCx       dd      4
_buttonCy       dd      2
_buttonCw       dd      14
_buttonCh       dd      16
   
_buttonMx       dd      24
_buttonMy       dd      2
_buttonMw       dd      17
_buttonMh       dd      18
   
_buttonPx       dd      41
_buttonPy       dd      2
_buttonPw       dd      17
_buttonPh       dd      18
   
_colorframe     dd      0x007799ff
_colorborder    dd      0x004466ff
_coloroutborder dd      0x002244ff
   
_fileleft       db      'LEFT.RAW     '
_filebase       db      'BASE.RAW     '
_fileoper       db      'OPER.RAW     '
   
_skinwinw       dd      0
   
   
   
   
